// tslint:disable no-type-definitions-outside-types-modules

enum Id {
    BAPBO = 'BAPBO',
    BEATEN_PATH = 'BEATEN_PATH',
    HAFUHAFU = 'HAFUHAFU',
    HOUNDSTOOTHTOPIA_THEME = 'HOUNDSTOOTHTOPIA_THEME',
    MATERIAL_QA = 'MATERIAL_QA',
    MATERIAL_QA_DELAY = 'MATERIAL_QA_DELAY',
    MET_MOS = 'MET_MOS',
    MOEOM = 'MOEOM',
    OMNIZONK = 'OMNIZONK',
    PLAYROOM_TEST_FINITE = 'PLAYROOM_TEST_FINITE',
    PLAYROOM_TEST_REPETEND = 'PLAYROOM_TEST_REPETEND',
    PLAYROOM_TEST_LONG_DURATION = 'PLAYROOM_TEST_LONG_DURATION',
    PLAYROOM_TEST_ONLY_PATTERN_PARTICULAR_SPECS = 'PLAYROOM_TEST_ONLY_PATTERN_PARTICULAR_SPECS',
    PLAYROOM_TEST_ONLY_STANDARD_SPECS = 'PLAYROOM_TEST_ONLY_STANDARD_SPECS',
    PLAYROOM_TEST_POST = 'PLAYROOM_TEST_POST',
    PLAYROOM_TEST_PRESETS = 'PLAYROOM_TEST_PRESETS',
    PLAYROOM_TEST_RESTART = 'PLAYROOM_TEST_RESTART',
    PLAYROOM_TEST_SPEC_CONTROLS = 'PLAYROOM_TEST_SPEC_CONTROLS',
    PLAYROOM_TEST_TIME_CONTROLS = 'PLAYROOM_TEST_TIME_CONTROLS',
    PLAYROOM_TEST_VALIDATION = 'PLAYROOM_TEST_VALIDATION',
    PROTOTYPER = 'PROTOTYPER',
    STEPWISE = 'STEPWISE',
    TEMPLATE = 'TEMPLATE',
    TSRAXCFAUBDJ = 'TSRAXCFAUBDJ',
    XENHARMONIC_SERIES = 'XENHARMONIC_SERIES',
    ZDAUBYAOS = 'ZDAUBYAOS',
}

export {
    Id,
}
